#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""Check that pipeline/stacks.yml, the templates on disk, and pipeline.yml all agree.

Run this through `tools/check` rather than directly -- the inline script metadata above lets
`uv run` fetch pyyaml on demand, so there is nothing to install and no venv to activate.

Run with no arguments to validate; run with --list to print the registered template paths
(what PR checks feeds to cfn-lint).

Two invariants, each checked in both directions:

registry <-> filesystem
    A template nobody registered is a template nobody lints, and a registry entry with no
    file is a stack the pipeline fails to deploy at merge time rather than at review time.

registry <-> pipeline.yml
    A `deployed_by: pipeline` entry with no CloudFormation action deploys nothing, and does
    so *silently* -- PR checks pass, every pipeline stage reports Succeeded, and no stack
    appears. Adding the action is step 3 of "Adding a blueprint stack" in pipeline/README.md;
    this is what makes forgetting it a review-time error instead of a mystery.

registry <- blueprint manifests
    A blueprint.yaml is the contract blueprint_search hands a builder, so one naming an
    unregistered template advertises a blueprint whose deployment PR cannot deploy. Checked
    one direction only: a template with no manifest is normal (builder-mcp is platform
    infrastructure, not a catalog entry).

terraform modules <-> pipeline.yml
    The same failure, one directory over. Terraform modules are not CloudFormation and so are
    not in the registry at all, which would leave a `blueprints/<name>/infra/azure/` directory
    with no Terraform action applying nothing while every stage still reported Succeeded.
    Checked in both directions against the TF_WORKING_DIR values in the pipeline's Terraform
    actions.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = REPO_ROOT / 'pipeline' / 'stacks.yml'
PIPELINE_PATH = REPO_ROOT / 'pipeline' / 'pipeline.yml'
BLUEPRINTS_DIR = REPO_ROOT / 'blueprints'

# CloudFormation deploy actions name their template as
# `TemplatePath: 'GitRepositoryArtifact::<repo-relative-path>'`. Matched by text scan for the
# same reason discover_templates() uses one: pipeline.yml is full of CloudFormation short tags
# (!Sub, !GetAtt) that yaml.safe_load cannot parse without a custom loader.
TEMPLATE_PATH_PATTERN = re.compile(r'GitRepositoryArtifact::([^\s\'"]+)')

# Terraform stage actions name their module as a CodeBuild environment-variable override,
# {"name":"TF_WORKING_DIR","value":"<repo-relative-path>",...}. Matched by text scan for the
# same reason as above: pipeline.yml cannot be yaml.safe_load'ed.
TF_WORKING_DIR_PATTERN = re.compile(r'"name"\s*:\s*"TF_WORKING_DIR"\s*,\s*"value"\s*:\s*"([^"]+)"')

# Terraform modules live alongside a blueprint's CloudFormation, per blueprints/README.md.
TF_MODULE_GLOB = 'blueprints/*/infra/azure'

# A YAML file is a CloudFormation template if it declares a template format version. Cheap
# text scan rather than a YAML parse, because CloudFormation short tags (!Sub, !GetAtt)
# are not loadable by yaml.safe_load without a custom loader.
TEMPLATE_MARKER = 'AWSTemplateFormatVersion'

# Directories with no deployable templates in them.
#
# outputs-preview/ is generated by packages/builder-mcp/devtools/preview_deploy.py and holds
# verbatim *copies* of blueprint templates, so the marker scan below would discover them as
# unregistered templates and fail the build. It is gitignored, but this scan walks the
# filesystem rather than git, so ignoring it there is not enough -- without this entry,
# running the preview tool breaks tools/check on that machine until the folder is deleted.
SKIP_DIRS = {
    '.git', '.github', 'node_modules', '.venv', '__pycache__', 'outputs-preview',
}

VALID_DEPLOYED_BY = {'pipeline', 'manual'}


def discover_templates() -> set[str]:
    """Every CloudFormation template in the repo, as repo-relative posix paths."""
    found = set()
    for path in REPO_ROOT.rglob('*'):
        if path.suffix not in {'.yml', '.yaml'} or not path.is_file():
            continue
        if SKIP_DIRS & set(path.relative_to(REPO_ROOT).parts):
            continue
        try:
            if TEMPLATE_MARKER in path.read_text(encoding='utf-8'):
                found.add(path.relative_to(REPO_ROOT).as_posix())
        except UnicodeDecodeError:
            continue
    return found


def pipeline_deployed_templates() -> set[str]:
    """Every template path a CloudFormation action in pipeline/pipeline.yml deploys."""
    if not PIPELINE_PATH.is_file():
        return set()
    text = PIPELINE_PATH.read_text(encoding='utf-8')
    return set(TEMPLATE_PATH_PATTERN.findall(text))


def discover_tf_modules() -> set[str]:
    """Every Terraform module in the repo, as repo-relative posix paths.

    A directory only counts once it holds at least one .tf file -- an empty directory is
    something in progress, not a module the pipeline should be applying.
    """
    return {
        path.relative_to(REPO_ROOT).as_posix()
        for path in REPO_ROOT.glob(TF_MODULE_GLOB)
        if path.is_dir() and any(path.glob('*.tf'))
    }


def pipeline_applied_tf_modules() -> set[str]:
    """Every Terraform module a Terraform action in pipeline/pipeline.yml applies."""
    if not PIPELINE_PATH.is_file():
        return set()
    text = PIPELINE_PATH.read_text(encoding='utf-8')
    return set(TF_WORKING_DIR_PATTERN.findall(text))


def check_tf_modules() -> list[str]:
    """Cross-check Terraform modules on disk against the pipeline's Terraform actions.

    Same silent failure as check_pipeline_actions, for the half of the deploy path that has no
    registry: a module nobody applies, or an action pointing at a directory that isn't there.
    """
    errors: list[str] = []
    on_disk = discover_tf_modules()
    applied = pipeline_applied_tf_modules()

    for orphan in sorted(on_disk - applied):
        errors.append(
            f'Terraform module {orphan} has no TF_WORKING_DIR action in pipeline/pipeline.yml '
            '-- it would apply nothing, silently. Add a Terraform stage action (see "Adding a '
            'Terraform module" in pipeline/README.md), or delete the module.'
        )

    for missing in sorted(applied - on_disk):
        path = REPO_ROOT / missing
        why = 'directory does not exist' if not path.is_dir() else 'directory contains no .tf files'
        errors.append(
            f'pipeline/pipeline.yml applies Terraform in {missing}, but that {why} '
            '-- the Terraform stage would fail after merge.'
        )

    return errors


def load_registry() -> list[dict]:
    if not REGISTRY_PATH.exists():
        sys.exit(f'missing registry: {REGISTRY_PATH.relative_to(REPO_ROOT)}')
    registry = yaml.safe_load(REGISTRY_PATH.read_text(encoding='utf-8')) or {}
    entries = registry.get('templates')
    if not isinstance(entries, list) or not entries:
        sys.exit('pipeline/stacks.yml must define a non-empty "templates" list')
    return entries


def validate(entries: list[dict]) -> list[str]:
    errors: list[str] = []
    seen_names: set[str] = set()
    seen_paths: set[str] = set()
    # template path -> deployed_by, for the pipeline.yml cross-check below.
    declared: dict[str, str] = {}

    for index, entry in enumerate(entries):
        where = f'templates[{index}]'
        if not isinstance(entry, dict):
            errors.append(f'{where}: expected a mapping, got {type(entry).__name__}')
            continue

        name = entry.get('name')
        template = entry.get('template')
        deployed_by = entry.get('deployed_by')

        if not name:
            errors.append(f'{where}: missing "name"')
        elif name in seen_names:
            errors.append(f'{where}: duplicate name {name!r}')
        else:
            seen_names.add(name)

        if deployed_by not in VALID_DEPLOYED_BY:
            errors.append(
                f'{where} ({name}): deployed_by must be one of '
                f'{sorted(VALID_DEPLOYED_BY)}, got {deployed_by!r}'
            )

        if not template:
            errors.append(f'{where} ({name}): missing "template"')
            continue
        if template in seen_paths:
            errors.append(f'{where} ({name}): duplicate template path {template!r}')
        seen_paths.add(template)
        declared[template] = deployed_by

        path = REPO_ROOT / template
        if not path.is_file():
            errors.append(f'{where} ({name}): registered template does not exist: {template}')
        elif TEMPLATE_MARKER not in path.read_text(encoding='utf-8'):
            errors.append(
                f'{where} ({name}): {template} has no {TEMPLATE_MARKER} '
                'and so is not a CloudFormation template'
            )

    for orphan in sorted(discover_templates() - seen_paths):
        errors.append(
            f'unregistered CloudFormation template: {orphan} '
            '-- add it to pipeline/stacks.yml so PR checks lint it'
        )

    errors.extend(check_pipeline_actions(declared))
    errors.extend(check_blueprint_manifests(declared))
    errors.extend(check_tf_modules())

    return errors


def check_blueprint_manifests(declared: dict[str, str]) -> list[str]:
    """Check that every blueprints/*/blueprint.yaml names a registered template.

    The manifest is what blueprint_search returns to a builder, so one pointing at an
    unregistered -- or nonexistent -- template advertises a blueprint whose deployment_create
    produces a pull request that cannot deploy. Registration is also what gets the template
    linted, so this is the invariant the rest of this file enforces, seen from the catalog side.

    A manifest is not a CloudFormation template and is deliberately not registered itself:
    it declares no template format version, so discover_templates() does not see it.
    """
    errors: list[str] = []

    for manifest_path in sorted(BLUEPRINTS_DIR.glob('*/blueprint.yaml')):
        where = manifest_path.relative_to(REPO_ROOT).as_posix()
        try:
            manifest = yaml.safe_load(manifest_path.read_text(encoding='utf-8'))
        except yaml.YAMLError as exc:
            errors.append(f'{where}: not valid YAML: {exc}')
            continue

        if not isinstance(manifest, dict):
            errors.append(f'{where}: expected a mapping at the top level')
            continue

        template = manifest.get('template')
        if not template:
            errors.append(
                f'{where}: missing "template" -- a manifest has to name the CloudFormation '
                'template its blueprint deploys'
            )
        elif template not in declared:
            errors.append(
                f'{where}: template {template!r} is not registered in pipeline/stacks.yml '
                '-- blueprint_search would offer a blueprint whose deployment PR cannot '
                'deploy. Register the template, or add the manifest in the same PR that '
                'adds it.'
            )

    return errors


def check_pipeline_actions(declared: dict[str, str]) -> list[str]:
    """Cross-check the registry against the CloudFormation actions in pipeline/pipeline.yml.

    Catches the silent failure: a blueprint registered as `deployed_by: pipeline` with no
    action deploys nothing while every check and every pipeline stage still reports success.
    """
    errors: list[str] = []
    deployed = pipeline_deployed_templates()

    for template, deployed_by in sorted(declared.items()):
        if deployed_by == 'pipeline' and template not in deployed:
            errors.append(
                f'{template} is registered deployed_by: pipeline but no CloudFormation '
                'action in pipeline/pipeline.yml deploys it -- it would deploy nothing, '
                'silently. Add a BlueprintDeploy action (step 3 of "Adding a blueprint '
                'stack" in pipeline/README.md), or register it as deployed_by: manual.'
            )
        if deployed_by == 'manual' and template in deployed:
            errors.append(
                f'{template} is registered deployed_by: manual but pipeline/pipeline.yml '
                'deploys it -- change deployed_by to pipeline, or remove the action.'
            )

    for template in sorted(deployed - set(declared)):
        errors.append(
            f'pipeline/pipeline.yml deploys {template}, which is not in pipeline/stacks.yml '
            '-- register it so PR checks lint it before it reaches a deploy.'
        )

    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--list',
        action='store_true',
        help='print registered CloudFormation template paths, one per line, instead of validating',
    )
    parser.add_argument(
        '--list-tf',
        action='store_true',
        help='print Terraform module directories, one per line, instead of validating',
    )
    args = parser.parse_args()

    # Kept out of the registry-loading path: tools/check calls this to find directories to
    # fmt and validate, and a broken stacks.yml should not stop Terraform from being linted.
    if args.list_tf:
        for module in sorted(discover_tf_modules()):
            print(module)
        return 0

    entries = load_registry()

    if args.list:
        # LF regardless of platform. tools/check word-splits this output into cfn-lint's
        # arguments, and on Windows print() would emit CRLF -- leaving a trailing carriage
        # return on every path but the last. cfn-lint then reports 'E0003 <template> could not
        # be processed by glob.glob', which reads like a broken template rather than a broken
        # path, and tools/check cannot pass on a Windows checkout at all.
        sys.stdout.reconfigure(newline='\n')
        for entry in entries:
            if isinstance(entry, dict) and entry.get('template'):
                print(entry['template'])
        return 0

    errors = validate(entries)
    if errors:
        print(f'stack and module registry: {len(errors)} problem(s)', file=sys.stderr)
        for error in errors:
            print(f'  - {error}', file=sys.stderr)
        return 1

    print(f'pipeline/stacks.yml: {len(entries)} template(s) registered and present')
    deployed = pipeline_deployed_templates()
    for entry in entries:
        # Showing which templates an action actually deploys makes step 3 of "Adding a
        # blueprint stack" visible rather than something you find out by its absence.
        wired = ' <- deployed by a pipeline action' if entry['template'] in deployed else ''
        print(f"  {entry['deployed_by']:<9} {entry['template']}{wired}")

    modules = discover_tf_modules()
    applied = pipeline_applied_tf_modules()
    print(f'terraform: {len(modules)} module(s) present')
    for module in sorted(modules):
        wired = ' <- applied by a pipeline action' if module in applied else ''
        print(f'  {"terraform":<9} {module}{wired}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
